# ~/.config/starship.toml

# Prompt format
format = """
[┌─](bold blue)[[%username%  %hostname% ](bold blue) [%directory%] [ %custom_ip%] $git_branch$git_status]
[└─](bold blue)$character
"""

# Multi-line prompt
add_newline = true

[line_break]
disabled = false

# Username
[username]
format = "[$user]"
show_always = true
style_user = "bold blue"
style_root = "bold red"

# Hostname
[hostname]
format = "[$hostname]"
ssh_only = false
style = "bold blue"

# Directory with path shortening
[directory]
truncate_to_repo = false
truncation_length = 5
format = "[ $path]($style)"
style = "bold cyan"
truncation_symbol = "..."

# Custom IP detection (using shell command)
[custom_ip]
command = '''
if ifconfig tun0 2>/dev/null | grep inet; then
  ifconfig tun0 | awk "/inet / {print \$2}"
elif ifconfig wlan0 2>/dev/null | grep inet; then
  ifconfig wlan0 | awk "/inet / {print \$2}"
else
  echo "No IP"
fi
'''
when = "true"
format = '[ $output](green)'

# Git branch
[git_branch]
format = "[$branch](yellow)"

# Git status
[git_status]
format = "[$all_status](red)"

# Character (prompt symbol)
[character]
success_symbol = "[\$](bold green)"
error_symbol = "[\$](bold red)"

# Exit code (shows on error)
[status]
format = "[Exit $status](red)"
disabled = false

# Optional: use nerd font symbols for more icons.
[env_var.USER]
disabled = false

# You can use other modules for extra info, see https://starship.rs/config/
